module umi_mux_8_to_1
  #(parameter DW = 128,
    parameter CW = 32,
    parameter AW = 32
    )
   (// controls
    input             clk,
    input             nreset,
    input [1:0]       arbmode,
    input [7:0]       arbmask,
    // UMI input 0
    input             umi_in0_valid,
    input [CW-1:0]    umi_in0_cmd,
    input [AW-1:0]    umi_in0_dstaddr,
    input [AW-1:0]    umi_in0_srcaddr,
    input [DW-1:0]    umi_in0_data,
    output            umi_in0_ready,
    // UMI input 1
    input             umi_in1_valid,
    input [CW-1:0]    umi_in1_cmd,
    input [AW-1:0]    umi_in1_dstaddr,
    input [AW-1:0]    umi_in1_srcaddr,
    input [DW-1:0]    umi_in1_data,
    output            umi_in1_ready,
    // UMI input 2
    input             umi_in2_valid,
    input [CW-1:0]    umi_in2_cmd,
    input [AW-1:0]    umi_in2_dstaddr,
    input [AW-1:0]    umi_in2_srcaddr,
    input [DW-1:0]    umi_in2_data,
    output            umi_in2_ready,
    // UMI input 3
    input             umi_in3_valid,
    input [CW-1:0]    umi_in3_cmd,
    input [AW-1:0]    umi_in3_dstaddr,
    input [AW-1:0]    umi_in3_srcaddr,
    input [DW-1:0]    umi_in3_data,
    output            umi_in3_ready,
    // UMI input 4
    input             umi_in4_valid,
    input [CW-1:0]    umi_in4_cmd,
    input [AW-1:0]    umi_in4_dstaddr,
    input [AW-1:0]    umi_in4_srcaddr,
    input [DW-1:0]    umi_in4_data,
    output            umi_in4_ready,
    // UMI input 5
    input             umi_in5_valid,
    input [CW-1:0]    umi_in5_cmd,
    input [AW-1:0]    umi_in5_dstaddr,
    input [AW-1:0]    umi_in5_srcaddr,
    input [DW-1:0]    umi_in5_data,
    output            umi_in5_ready,
    // UMI input 6
    input             umi_in6_valid,
    input [CW-1:0]    umi_in6_cmd,
    input [AW-1:0]    umi_in6_dstaddr,
    input [AW-1:0]    umi_in6_srcaddr,
    input [DW-1:0]    umi_in6_data,
    output            umi_in6_ready,
    // UMI input 7
    input             umi_in7_valid,
    input [CW-1:0]    umi_in7_cmd,
    input [AW-1:0]    umi_in7_dstaddr,
    input [AW-1:0]    umi_in7_srcaddr,
    input [DW-1:0]    umi_in7_data,
    output            umi_in7_ready,
    // outgoing UMI
    output            umi_out_valid,
    output [CW-1:0]   umi_out_cmd,
    output [AW-1:0]   umi_out_dstaddr,
    output [AW-1:0]   umi_out_srcaddr,
    output [DW-1:0]   umi_out_data,
    input             umi_out_ready
    );

   umi_mux #(.N(8),
              .DW(DW),
              .CW(CW),
              .AW(AW))
   umi_mux_i (// controls
               .clk            (clk),
               .nreset         (nreset),
               .arbmode        (arbmode[1:0]),
               .arbmask        (arbmask[7:0]),
               // incoming UMI (concatenated, index 0 at LSB)
               .umi_in_valid   ({umi_in7_valid,
                                 umi_in6_valid,
                                 umi_in5_valid,
                                 umi_in4_valid,
                                 umi_in3_valid,
                                 umi_in2_valid,
                                 umi_in1_valid,
                                 umi_in0_valid}),
               .umi_in_cmd     ({umi_in7_cmd,
                                 umi_in6_cmd,
                                 umi_in5_cmd,
                                 umi_in4_cmd,
                                 umi_in3_cmd,
                                 umi_in2_cmd,
                                 umi_in1_cmd,
                                 umi_in0_cmd}),
               .umi_in_dstaddr ({umi_in7_dstaddr,
                                 umi_in6_dstaddr,
                                 umi_in5_dstaddr,
                                 umi_in4_dstaddr,
                                 umi_in3_dstaddr,
                                 umi_in2_dstaddr,
                                 umi_in1_dstaddr,
                                 umi_in0_dstaddr}),
               .umi_in_srcaddr ({umi_in7_srcaddr,
                                 umi_in6_srcaddr,
                                 umi_in5_srcaddr,
                                 umi_in4_srcaddr,
                                 umi_in3_srcaddr,
                                 umi_in2_srcaddr,
                                 umi_in1_srcaddr,
                                 umi_in0_srcaddr}),
               .umi_in_data    ({umi_in7_data,
                                 umi_in6_data,
                                 umi_in5_data,
                                 umi_in4_data,
                                 umi_in3_data,
                                 umi_in2_data,
                                 umi_in1_data,
                                 umi_in0_data}),
               .umi_in_ready   ({umi_in7_ready,
                                 umi_in6_ready,
                                 umi_in5_ready,
                                 umi_in4_ready,
                                 umi_in3_ready,
                                 umi_in2_ready,
                                 umi_in1_ready,
                                 umi_in0_ready}),
               // outgoing UMI
               .umi_out_valid  (umi_out_valid),
               .umi_out_cmd    (umi_out_cmd),
               .umi_out_dstaddr(umi_out_dstaddr),
               .umi_out_srcaddr(umi_out_srcaddr),
               .umi_out_data   (umi_out_data),
               .umi_out_ready  (umi_out_ready));

endmodule
