name: Testbench CI
on:
  # Runs on all PRs
  pull_request:
  # Manual Dispatch
  workflow_dispatch:

jobs:
  switchboard_ci:
    name: "Switchboard CI"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/zeroasiccorp/sbtest:latest
    timeout-minutes: 45

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: pytest
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          python3 -m venv venv
          . venv/bin/activate
          python3 -m pip install --upgrade pip
          python3 -m pip install -e .[test]
          pytest -m "switchboard" -x --verbose --durations=0


  cocotb_ci:
    name: "Cocotb CI"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/siliconcompiler/sc_runner:latest
    timeout-minutes: 45

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: pytest
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          python3 -m venv venv
          . venv/bin/activate
          python3 -m pip install --upgrade pip
          python3 -m pip install -e .[test]
          pytest -m "cocotb" -x --verbose --durations=0


  python_ci:
    name: "Python + Tools CI"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/siliconcompiler/sc_tools:latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: pytest
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          python3 -m venv venv
          . venv/bin/activate
          python3 -m pip install --upgrade pip
          python3 -m pip install -e .[test]
          pytest -m "not switchboard and not cocotb" -n logical --verbose
