name: Wheels

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  build_wheels:
    name: Wheels UMI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
      with:
        submodules: true
    - uses: hynek/build-and-inspect-python-package@v2

  publish:
    needs: [build_wheels]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    if: github.event_name == 'release' && github.event.action == 'published'

    steps:
    - uses: actions/download-artifact@v6
      with:
        name: Packages
        path: dist

    - name: Publish
      uses: pypa/gh-action-pypi-publish@v1.13.0

  save:
    needs: [publish]
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/download-artifact@v6
      with:
        name: Packages
        path: dist

    - name: Add wheels to GitHub release artifacts
      uses: softprops/action-gh-release@v2
      with:
        files: dist/*.whl
